// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

void* winrt_make_MazeGen_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::MazeGen::factory_implementation::MainPage>());
}
WINRT_EXPORT namespace winrt::MazeGen
{
    MainPage::MainPage() :
        MainPage(make<MazeGen::implementation::MainPage>())
    {
    }
}
