// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

void* winrt_make_MazeGen_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::MazeGen::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::MazeGen
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<MazeGen::implementation::XamlMetaDataProvider>())
    {
    }
}
