// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_MazeGen_0_H
#define WINRT_MazeGen_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::MazeGen
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::MazeGen::IMainPage>{ using type = interface_category; };
    template <> struct category<winrt::MazeGen::MainPage>{ using type = class_category; };
    template <> struct category<winrt::MazeGen::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::MazeGen::MainPage> = L"MazeGen.MainPage";
    template <> inline constexpr auto& name_v<winrt::MazeGen::XamlMetaDataProvider> = L"MazeGen.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::MazeGen::IMainPage> = L"MazeGen.IMainPage";
    template <> inline constexpr guid guid_v<winrt::MazeGen::IMainPage>{ 0xD4C53E67,0xF1A0,0x51AE,{ 0x90,0xC7,0x0D,0x21,0x76,0x23,0x59,0xF7 } }; // D4C53E67-F1A0-51AE-90C7-0D21762359F7
    template <> struct default_interface<winrt::MazeGen::MainPage>{ using type = winrt::MazeGen::IMainPage; };
    template <> struct default_interface<winrt::MazeGen::XamlMetaDataProvider>{ using type = winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::MazeGen::IMainPage>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_MazeGen_IMainPage
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int32_t) MyProperty() const;
        WINRT_IMPL_AUTO(void) MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::MazeGen::IMainPage>
    {
        template <typename D> using type = consume_MazeGen_IMainPage<D>;
    };
}
#endif
